# Generated by Django 4.0.1 on 2022-01-15 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='all_salary',
            field=models.FloatField(default=0, verbose_name='Выплачено ЗП'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_amount',
            field=models.FloatField(default=0, verbose_name='Размер ЗП'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Созд. пользователь'),
        ),
    ]
